---
title: "Assignment 5: Analyzing repeated measured experiments"
author: "Sivert Helland Veseth"
format: 
  html:
    number-sections: true
    toc: true
    code-fold: true
execute: 
  warning: false
crossref:
  fig-title: "Figur"
  tbl-title: "Tabell"
bibliography: resources/referanser.bib
csl: resources/apa.csl
---

Mulig hypotese:

-   Vil størst endring i lean body mass også tilsvare størst endring i styrke?

# Introduksjon

Avsnitt 1:

Treningsadaptasjon er en av de mest grunnleggende søylene i treningsvitenskapen,
som sier at kroppen vår kan tilpasse seg den belastningen den utsettes for, gitt at den får nok tid til å tilpasse seg den nye belastningen (@bompa2019, s. 8). Spesielt skjelettmuskulaturen har vist seg å være et høgts tilpasningsdyktig vev som kan endre sin egen arkitektur som respons på en gitt stimuli (@coffey2007). Resultatene på disse tilpasningene er påvirket av volumet, intensiteten og frekvensen av treningen, i tillegg vil tilpasningene avhengig av den spesifikke belastningen kroppen og muskulaturen utsettes for, for eksempel treningsmetode (@bompa2019, s.3; @Raastad2010, s.17;@coffey2007;@izquierdo2004). 

Styrketrening har vist seg å være avgjørende, ikke bare for idrettsprestasjoner (@washif2022), men også for folkehelse og redusert dødelighet (@ruiz2008). Denne treningsformen omfatter aktiviteter som utvikler eller opprettholder vår evne til å generer maksimal kraft eller dreiemoment ved en spesifikk hastighet (@Raastad2010, s.17). Trening for maksimal muskelstyrke, der målet er å øke den høyeste kraften en muskel kan produsere (@Raastad2010, s.13), skiller seg fra trening med hensikt om muskelvekst (hypertrofi), hvor fokus ligger på å øke muskelens størrelse (@schoenfeld2016). Flere studier har undersøkt hvilket treningsvolum som best stimulerer slike tilpasninger og har identifisert et dose-respons-forhold, hvor økt treningsvolum er assosiert med større muskelvekst (@currier2023; @schoenfeld2016). Et lignende forhold er også blitt observert for muskelstyrke (@ralston2017), selv om det er også foreslått at et høgt treningsvolum kan bremse utviklingen av maksimal muskelstyrke (@zhang2023). Muskelens tverrsnitt er en sentral faktor å ta med, da et større tverrsnitt vil gi et større potensiale for kraftutvikling (@Raastad2010, s.20). Dette understreker behovet for videre undersøkelser av hvordan treningsvolum påvirker både muskelhypertrofi og styrkeutvikling, samt i hvilken grad endringer i muskelmasse er sammenfallende med økninger i styrke.


På bakgrunn av tidligere forskning og den noe usikre dose-respons-sammenhengen mellom optimal treningsvolum og muskeltilpasninger, er formålet med denne studien å undersøke hvordan ulike nivåer av treningsvolum påvirker både muskelvekst og muskelstyrke. Ettersom at skjelettmuskulaturen er svært tilpasningsdyktig på den stimulien utsettes for, ønsker studien også å undersøke om større endringer i muskelvekst følger sammen med tilsvarende endringer i muskelstyrke ved høyere treningsvolum. Ved å utforske denne sammenhengen håper man å kunne bidra med økt innsikt som kan være nyttig ved anbefalinger om optimalt treningsvolum. 


- Introdusere leseren for kva som skal bli undersøkt. Sentrale punkter å få med er:
  - Hensikten med trening generelt, og knytt det opp mot styrketrening - kva er dette? For inspirasjon se eksamensoppgåve     i styrkefaget.
  - Forholdet mellom økt lean body mass og styrketrening (dose-respons forholdet)- tett knyttet til hverandre, samtidig      som det ses en diskrepans når man sammenligner dose-respons forholdet på lean body mass og muskelstyrke. 

Avsnitt 2:

- Benytt dette avsnittet til å forklare mer i detalj mekanismene bak økning i lean body mass og muskelstyrke. Sentrale definisjoner å få inn vil være
  - Lean body mass
  - Muskelstyrke, maksimal styrke
  - Hva er det som er med å bestemme muskelstyrken vår (se Raastad for inspirasjon)
  - Dose-respons forholdet
  - Treningsvolum
  - Kan være fint å få inn intensitet og grad av anstrengelse

Avsnitt 3:

- Mange som argumenterer for at tverrsnitsarealet av muskulatur er den viktigaste faktoren for vår maksimale styrke. Utfordrer derfor dette synet, og ønsker å se på om økning i muskelmasse kan være et godt mål på økning i muskelstyrke.
  
# Metode

Få med følgende deler:

- Participants and study overview: Describe the participants and give an overview of all tests/measurements. Participants should be described in the first table of the report (Table 1). The overview of the tests/measurements should be done without double presentation as details should be presented in subsequent sections.

- Specific descriptions (e.g. strength tests): Describe in detail how tests/measurements that you mentioned in the overview where conducted.

- Data analysis and statistics: Describe how you treated the data prior to statistical tests or procedures and what tests/procedures were used to draw inference (or more generally, to answer your purpose). Describe how you present data (e.g. descriptive data with mean (SD), inference with confidence intervals etc.).

# Resulater

# Diskusjon


